env:
 sim_length: 82

curriculum:
 curr_laps: 6
 window_size: 50
 threshold_for_increase: 0.7

 min_workspace_area: 0.02
 max_workspace_area: 0.15

 min_gripper_height: 0.09
 max_gripper_height: 0.25

 min_picking_height: 0.02
 max_picking_height: 0.10

camera:
 height: 64
 width: 64
 near: 0.003 #near, far = 0.02, 2.0 #thesis
 far: 1.0
 fov: 120
 
 
