env:
 sim_length: 64
 sr_window_size: 50

curriculum:
 curr_laps: 8
 threshold_for_increase: 0.4

 min_workspace_area: 0.02
 max_workspace_area: 0.18

 min_gripper_height: 0.10
 max_gripper_height: 0.22

 min_lifting_height: 0.02
 max_lifting_height: 0.10

camera:
 height: 128
 width: 128
 near: 0.003 #near, far = 0.02, 2.0 #thesis
 far: 1.0
 fov: 90
 
 
